<?php
/**
 * Created by PhpStorm.
 * Author: SYes
 * Date: 2017/4/23
 * Time: 20:41
 */
namespace app\Model;

use core\lib\model;

class cModel extends model
{
    public $table = 'c';

    /**
     * @param $columns  string/array  查询的列
     * @param $where    array   查询条件
     * @return array
     */
    public function all($columns = '*', $where = null)
    {
        $res = $this->select($this->table, $columns, $where);
        return $res;
    }

    public function getOne($id)
    {
        $res = $this->get($this->table, '*', [
            'id' => $id
        ]);
        return $res;
    }

    public function update($table, $data, $where = null)
    {
        return parent::update($table, $data, $where); // TODO: Change the autogenerated stub
    }
}